### ISSUE TITLE
About pre-trained model weights

### ISSUE THREAD

**Issue by Takersflames** [ShuvenduRoy/CoPrompt#2]
I came across your paper at ICLR 2024 and was truly fascinated by your exceptional work. I was wondering if there are any available model weights or training logs. I would greatly appreciate your response.

**Comment by ShuvenduRoy** [comment]
Hi, Thanks for your interest. This work uses pre-trained CLIP weight to fine-tune on downstream tasks. We do not plan to release any task-specific checkout or other assets.
